site_name: JoÃ£o Vitor Luz
site_url: https://vitorluzz.github.io
copyright: Copyright &copy; 2025 - JoÃ£o Vitor Luz Campos


theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - header.autohide
    - navigation.footer


  palette: 

    # Palette toggle for light mode
    - scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
    generator: false
    social:
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/jo%C3%A3o-vitor-luz-6b2109340/
        name: Linkedin
      - icon: fontawesome/brands/github
        link: https://github.com/vitorluzz
        name: GitHub

nav:
  - "ğŸ  Home": index.md
  -  "ğŸ“– IntroduÃ§Ã£o":
      - "ğŸ‘¤ Sobre mim": sobre.md
      - "ğŸ“š Treinamentos": treinamentos.md
  - "ğŸ”CiÃªncia de Dados":
      - "âœ¨ IntroduÃ§Ã£o":
          - "ğŸ‘£ Primeiro Passo": dadoinformacaoconhecimento.md
          - "ğŸ“Œ Conceitos bÃ¡sicos": fundamentosdatascience.md
  - "ğŸ’» Engenharia de Dados":
      - "âœ¨ IntroduÃ§Ã£o":
          - "ğŸ‘£ Primeiro Passo": dadoinformacaoconhecimento.md
          - "ğŸ“Œ Conceitos bÃ¡sicos": oqeengenharia.md
      - "ğŸš€ Pipeline de Dados": pipelinedados.md
      - "ğŸ’¾ Armazenamento de Dados": armazenamentodados.md
      - "ğŸŒ Sistemas DistribuÃ­dos": sistemasdistribuidos.md
      - "ğŸ—ï¸ Data Warehouse, Data Lake e Data Lakehouse": tiposbd.md
      - "ğŸ“Š Modelagem de Dados": modelagemdados.md
      - "âœ… Data Quality": data_quality.md
      - "ğŸ› ï¸ Data Ops / Dev Ops": dataops.md
      - "ğŸ” Data Observability": dataobservar.md
      
  - "ğŸ Python":
      - "ğŸ“Œ Fundamentos Python":
          - "Conceitos BÃ¡sicos": conceitosbasicospy.md
          - "Primeiros Passos": python.md
      - "ğŸ“¦ OrientaÃ§Ã£o a Objeto (POO)": poo.md
      - "ğŸ”¢ Numpy": 
          - "Primeiros Passos": comeconumpy.md
          - "IndexaÃ§Ã£o em Arrays": indexacaonumpy.md
          - "Manipulando Matrizes": manipulandomatriz.md
          - "Manipulando Objetos 3D e 4D": manipulandoobjetos.md
          - "Manipulando Arquivos": manipulandoarquivosnumpy.md
          - "AnÃ¡lise EstatÃ­stica": analiseestatisticanumpy.md
          - "OperaÃ§Ãµes MatemÃ¡ticas": operacoesmatematicas.md
          - "ManipulaÃ§Ã£o Arrays": manipulandoarrays.md
      - "ğŸ“Š Pandas": 
          - "Primeiros Passos": pandas.md
          - "Manipulando DataFrames": manipulandodataframe.md
          - "Utilizando NumPy com Pandas": numpycompandas.md
          - "Fatiamento de DataFrame (Slicing)": fatiamentodataframe.md
          - "Manipulando Valores Ausentes": valoresausentes.md
          - "Query's em DataFrame Pandas": querypandas.md
          - "Verificando OcorrÃªncias de Valores": verificandoocorrencias.md
          - "Operadores LÃ³gicos": operadoreslogicos.md
          - "Agrupamento de Dados com GroupBy": agrupandodados.md
          - "Filtrando com Strings": filtrandostring.md
          - "Slipt de Strings": splitstrings.md
          - "Strip em DFs": stripdf.md
          - "Replace de Strings": replacedf.md
          - "CombinaÃ§Ã£o de Strings": combinacaodf.md
          - "ConstruÃ§Ã£o de GrÃ¡ficos com Pandas": graficopandas.md
      - "ğŸ“ˆ MatPlotLib e SeaBorn": 
          - "Por que utilizar?": mtpl_sb.md
          - "MatPlotLib": mtpl.md
          - "PyLab": pylab.md
          - "SeaBorn": seaborn.md
          - "Combinando MTPL, SB, PD, NP na criaÃ§Ã£o de grÃ¡ficos": combinando.md
      - "ğŸ” SQL":
          - "Conceitos bÃ¡sicos": sql.md
          - "Utilizando Python para trabalhar com Linguagem SQL": pythonsql.md
          - "Utilizando o Pandas para trabalhar com Linguagem SQL": pandassql.md
          - "Sintaxe SQL X Sintaxe Pandas": sintaxepysql.md
