site_name: JoÃ£o Vitor Luz
site_url: https://vitorluzz.github.io
copyright: Copyright &copy; 2025 - JoÃ£o Vitor Luz Campos


theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - header.autohide
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.code.language
  palette: 

    # Palette toggle for light mode
    - scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - codehilite:
      guess_lang: false
  - pymdownx.highlight:
      linenums: false
      anchor_linenums: false
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra:
    generator: false
    social:
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/jo%C3%A3o-vitor-luz-6b2109340/
        name: Linkedin
      - icon: fontawesome/brands/github
        link: https://github.com/vitorluzz
        name: GitHub

nav:
  - "ğŸ  Home": home/index.md
  -  "ğŸ“– IntroduÃ§Ã£o":
      - "ğŸ‘¤ Sobre mim": introducao/sobre.md
      - "ğŸ“š Treinamentos": introducao/treinamentos.md
  - "ğŸ”CiÃªncia de Dados":
      - "âœ¨ IntroduÃ§Ã£o":
          - "ğŸ‘£ Primeiro Passo": cienciadados/introducao/dadoinformacaoconhecimento.md
          - "ğŸ“Œ Conceitos bÃ¡sicos": cienciadados/introducao/fundamentosdatascience.md
      - "ğŸ“Œ Data Science X EstatÃ­stica": cienciadados/dsestatistica.md
      - "Ciclo de Vida de Projetos": cienciadados/cicloprojetos.md
      - "ğŸ’» AplicaÃ§Ãµes e Ferramentas": 
          - "ğŸ“˜ IntroduÃ§Ã£o": cienciadados/aplicacoeseferramentas/introducaoferramentasds.md
          - "ğŸ› ï¸ Ferramentas":
              - "Principais Ferramentas": cienciadados/aplicacoeseferramentas/ferramentas/aplicacoesferramentasds.md
              - "Ferramentas Low-Code (VisualizaÃ§Ã£o)": cienciadados/aplicacoeseferramentas/ferramentas/ferramentaslowcodevisualizacao.md
  - "ğŸ’» Engenharia de Dados":
      - "âœ¨ IntroduÃ§Ã£o":
          - "ğŸ‘£ Primeiro Passo": engenhariadados/introducao/dadoinformacaoconhecimento.md
          - "ğŸ“Œ Conceitos bÃ¡sicos": engenhariadados/introducao/oqeengenharia.md
      - "ğŸš€ Pipeline de Dados": engenhariadados/pipelinedados.md
      - "ğŸ’¾ Armazenamento de Dados": engenhariadados/armazenamentodados.md
      - "ğŸŒ Sistemas DistribuÃ­dos": engenhariadados/sistemasdistribuidos.md
      - "ğŸ—ï¸ Data Warehouse, Data Lake e Data Lakehouse": engenhariadados/tiposbd.md
      - "ğŸ“Š Modelagem de Dados": engenhariadados/modelagemdados.md
      - "âœ… Data Quality": engenhariadados/data_quality.md
      - "ğŸ› ï¸ Data Ops / Dev Ops": engenhariadados/dataops.md
      - "ğŸ” Data Observability": engenhariadados/dataobservar.md
  - "ğŸ¤– InteligÃªncia Artificial": 
      - "Fundamentos da IA": inteligenciaartificial/inteligenciaartificial.md
      - "Machine Learning": inteligenciaartificial/machinelearning.md
      - "Engenharia de IA com Deep Learning e LLMs":
          - "Fundamentos de Redes Neurais Artificiais": inteligenciaartificial/engenharia/redesneurais.md
          - "Deep Learning e RevoluÃ§Ã£o em IA": inteligenciaartificial/engenharia/deeplearning.md
          - "Arquitetura de Transformadores": inteligenciaartificial/engenharia/transformadores.md
          - "Large Language Models (LLMs)": inteligenciaartificial/engenharia/llms.md
          - "Retrieval Augmented Generation (RAG)": inteligenciaartificial/engenharia/rag.md
  - "ğŸ Python":
      - "ğŸ“Œ Fundamentos Python":
          - "Conceitos BÃ¡sicos": python/fundamentospy/conceitosbasicospy.md
          - "Primeiros Passos": python/fundamentospy/python.md
      - "ğŸ“¦ OrientaÃ§Ã£o a Objeto (POO)": python/poo.md
      - "ğŸ”¢ Numpy": 
          - "Primeiros Passos": python/numpy/comeconumpy.md
          - "IndexaÃ§Ã£o em Arrays": python/numpy/indexacaonumpy.md
          - "Manipulando Matrizes": python/numpy/manipulandomatriz.md
          - "Manipulando Objetos 3D e 4D": python/numpy/manipulandoobjetos.md
          - "Manipulando Arquivos": python/numpy/manipulandoarquivosnumpy.md
          - "AnÃ¡lise EstatÃ­stica": python/numpy/analiseestatisticanumpy.md
          - "OperaÃ§Ãµes MatemÃ¡ticas": python/numpy/operacoesmatematicas.md
          - "ManipulaÃ§Ã£o Arrays": python/numpy/manipulandoarrays.md
      - "ğŸ“Š Pandas": 
          - "Primeiros Passos": python/pandas/pandas.md
          - "Manipulando DataFrames": python/pandas/manipulandodataframe.md
          - "Utilizando NumPy com Pandas": python/pandas/numpycompandas.md
          - "Fatiamento de DataFrame (Slicing)": python/pandas/fatiamentodataframe.md
          - "Manipulando Valores Ausentes": python/pandas/valoresausentes.md
          - "Query's em DataFrame Pandas": python/pandas/querypandas.md
          - "Verificando OcorrÃªncias de Valores": python/pandas/verificandoocorrencias.md
          - "Operadores LÃ³gicos": python/pandas/operadoreslogicos.md
          - "Agrupamento de Dados com GroupBy": python/pandas/agrupandodados.md
          - "Filtrando com Strings": python/pandas/filtrandostring.md
          - "Slipt de Strings": python/pandas/splitstrings.md
          - "Strip em DFs": python/pandas/stripdf.md
          - "Replace de Strings": python/pandas/replacedf.md
          - "CombinaÃ§Ã£o de Strings": python/pandas/combinacaodf.md
          - "ConstruÃ§Ã£o de GrÃ¡ficos com Pandas": python/pandas/graficopandas.md
      - "ğŸ“ˆ MatPlotLib e SeaBorn": 
          - "Por que utilizar?": python/mtplesb/mtpl_sb.md
          - "MatPlotLib": python/mtplesb/mtpl.md
          - "PyLab": python/mtplesb/pylab.md
          - "SeaBorn": python/mtplesb/seaborn.md
          - "Combinando MTPL, SB, PD, NP na criaÃ§Ã£o de grÃ¡ficos": python/mtplesb/combinando.md
      - "ğŸ” SQL":
          - "Conceitos bÃ¡sicos": python/sqlpy/sql.md
          - "Utilizando Python para trabalhar com Linguagem SQL": python/sqlpy/pythonsql.md
          - "Utilizando o Pandas para trabalhar com Linguagem SQL": python/sqlpy/pandassql.md
          - "Sintaxe SQL X Sintaxe Pandas": python/sqlpy/sintaxepysql.md
      - "â­ HACKS": python/hackspy.md
  - "ğŸ“Š Microsoft Power BI": 
          - "ğŸ“Œ IntroduÃ§Ã£o": powerbi/introducaopbi.md
  - "ğŸˆâ€ Git": git/git.md
  - "ğŸ“¦ DataBricks": databricks/databricks.md
  - "ğŸ§± MkDocs":
      - "ğŸ“˜ IntroduÃ§Ã£o": mkdocs/mkdocsintroducao.md
      - "ğŸ› ï¸ Criando um site com MkDocs Material":
          "ğŸ“– Criando o site": mkdocs/criandoprojeto/mkdocs_criando.md
          "âœï¸ Estilizando o site": mkdocs/criandoprojeto/mkdocs_estilizando.md
          "ğŸš€ Publicando o site no GitHub Pages": mkdocs/criandoprojeto/publicandoprojeto.md